### PR TITLE
Pad size 2 vectors to size 4 when lowering extern_elementwise ops

### PR DESCRIPTION
**Pull request by int3**
libsleef does not implement 2-element functions, so for libdevice functions implemented via extern_elementwise ops that rely wholly on libsleef implementations (as opposed to MathOps which can be lowered to native instructions), we need to pad those vectors to size 4.

This allows us to enable test_math.py for all the functions introduced in https://github.com/triton-lang/triton-cpu/pull/161.

### CODE REVIEW

File: third_party/cpu/lib/TritonCPUToLLVM/MathToVecLib.cpp [hunk 1]
```diff
@@ -136,6 +138,63 @@ struct DecomposeToNativeVecs : public OpRewritePattern<OpT> {
...
+    for (int i = 0; i < 4; ++i) {
+      if (i < numElems)
+        indices[i] = i;
+      else
+        indices[i] = numElems;
+    }
+    for (auto argVal : op.getOperands()) {
+      auto shuf =
+          rewriter.create<vector::ShuffleOp>(loc, argVal, paddingVec, indices);
+      rewriter.replaceAllUsesExcept(argVal, shuf, shuf);
```
Comment (ienkovich) [inline third_party/cpu/lib/TritonCPUToLLVM/MathToVecLib.cpp:184]: Here you can modify operations other than ExternElementwiseOp

Comment (int3) [reply third_party/cpu/lib/TritonCPUToLLVM/MathToVecLib.cpp]: oh right, good catch

**Review by minjang — APPROVED** [review]
looks good!
